name: Component Tests

on:
  push:
    branches: [main]
    paths:
      - "src/components/**"
      - "package.json"
      - "playwright-ct.config.ts"
      - ".github/workflows/component-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/components/**"
      - "package.json"
      - "playwright-ct.config.ts"
      - ".github/workflows/component-tests.yml"
  workflow_dispatch:

jobs:
  component-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run component tests
        run: pnpm test-ct:ci

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7
